[package]
name = "longyield"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
libp2p = "0.43.0"
tokio = { version = "1", features = ["full"] }
ring = "0.17"
rand = "0.8"
hex = "0.4"
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }